"""
Django settings for SmartArchive_Backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-am_3$an-me7!c6h6)k^9&63y#y9r5yws92m4w+v-ns-+=&ad6o"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    "comptes.apps.ComptesConfig",
    "etablissement.apps.EtablissementConfig",
    "dossiers.apps.DossiersConfig",
    "inscriptions.apps.InscriptionsConfig",
    "pedagogie.apps.PedagogieConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

ROOT_URLCONF = "SmartArchive_Backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SmartArchive_Backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "comptes.Utilisateur"


# Jazzmin Configuration


JAZZMIN_SETTINGS = {
    # Titre de la fenêtre
    "site_title": "SmartArchive Admin",
    # Titre sur l'écran de connexion
    "site_header": "SmartArchive",
    # Logo (placez un fichier 'logo.png' dans votre dossier static si vous en avez un)
    # "site_logo": "img/logo.png",
    # Message de bienvenue sur l'écran de login
    "welcome_sign": "Bienvenue sur SmartArchive",
    # Copyright en bas de page
    "copyright": "IIT School of Engineering",
    # Menu latéral (Avatar de l'utilisateur)
    "user_avatar": None,
    "navigation_expanded": False,
    # --- Personnalisation du Menu ---
    # Ordre des applications dans le menu latéral
    "order_with_respect_to": [
        "comptes",
        "inscriptions",
        "dossiers",
        "pedagogie",
        "etablissement",
    ],
    # Icônes pour vos applications (FontAwesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "comptes.Utilisateur": "fas fa-user",
        "comptes.Professeur": "fas fa-chalkboard-teacher",
        "comptes.Educateur": "fas fa-user-tie",
        "etablissement.Ecole": "fas fa-university",
        "etablissement.Classe": "fas fa-layer-group",
        "etablissement.Matiere": "fas fa-book",
        "etablissement.AnneeScolaire": "fas fa-calendar-alt",
        "dossiers.Eleve": "fas fa-user-graduate",
        "dossiers.Document": "fas fa-file-archive",
        "inscriptions.Inscription": "fas fa-file-signature",
        "pedagogie.Evaluation": "fas fa-pen-alt",
        "pedagogie.Note": "fas fa-star",
        "pedagogie.Bulletin": "fas fa-file-invoice",
    },
}

# Configuration de l'interface utilisateur (Couleurs)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "theme": "flatly",  # Thème moderne et propre
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
